services:
  db-1:
    image: postgres:15
    container_name: patient-db-1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: patient_db
      POSTGRES_HOST: localhost
    ports:
      - "5432:5432"
    volumes:
      - "./db-1:/var/lib/postgresql/data"
    networks:
        - db
volumes:
    db-1:
        driver: local
networks:
    db:
        driver: bridge
